# XOR with a feedforward neural network

In [1]:
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
W = np.mat('1.0, 1.0; 1.0, 1.0')
b = np.mat('0;-1')
x = [ np.mat('0;0'), np.mat('1;0'), np.mat('0;1'), np.mat('1;1') ]
for i, v in enumerate(x): 
    print("x_{}:\n{}".format(i, v))

x_0:
[[0]
 [0]]
x_1:
[[1]
 [0]]
x_2:
[[0]
 [1]]
x_3:
[[1]
 [1]]


In [3]:
z = list(map(lambda x: W * x + b, x))
for i, v in enumerate(z): 
    print("z_{}:\n{}".format(i, v))

z_0:
[[ 0.]
 [-1.]]
z_1:
[[1.]
 [0.]]
z_2:
[[1.]
 [0.]]
z_3:
[[2.]
 [1.]]


In [4]:
relu = lambda z: np.maximum(z,0)
h = list(map(relu, z))
for i, v in enumerate(h): 
    print("h_{}:\n{}".format(i, v))

h_0:
[[0.]
 [0.]]
h_1:
[[1.]
 [0.]]
h_2:
[[1.]
 [0.]]
h_3:
[[2.]
 [1.]]


In [5]:
u = np.mat('1,-2')
gamma = -0.5
results = list(map(lambda x: u * x + gamma, h))
for i in results:
    print(i)

[[-0.5]]
[[0.5]]
[[0.5]]
[[-0.5]]


In [46]:
from IPython.core.display import HTML

def css_styling():
    styles = open("../css/notebook.css", "r").read()
    return HTML(styles)
css_styling()